const ACTION_TYPES = {
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_SET_STEP: 'COUNTER_SET_STEP',

  SET_THEME: 'SET_THEME',

  GET_USER_ACTION: 'GET_USER_ACTION', // Загрузить
  GET_USER_REQUEST: 'GET_USER_REQUEST', // Гружу
  GET_USER_SUCCESS: 'GET_USER_SUCCESS', // Пришли данные
  GET_USER_ERROR: 'GET_USER_ERROR' // Пришла ошибка
}

export default ACTION_TYPES
