const ACTION_TYPES = {
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_SET_STEP: 'COUNTER_SET_STEP',
  SET_THEME: 'SET_THEME'
}

export default ACTION_TYPES
